Repository KDT-hahahoho/kdt_frontend, pull requests merged in 2024-10, with the labels that each got.

#3 깃 리뷰어스 기능을 테스트한다.
  src/App.tsx
Labels: Docs

#10 Chore : 폴더 구조를 생성하고 필요한 패키지를 설치한다.
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
  prompt/.env
  src/assets/logo.svg
  src/assets/react.svg
  src/components/Button.tsx
  src/features/Auth.tsx
  src/hooks/useFetch.tsx
  src/main.tsx
  src/pages/MainPage.tsx
  src/store/userStroe.ts
  src/styles/GlobalStyles.tsx
  src/styles/theme.js
  src/utils/constants.js
  vite.config.ts
Labels: Chore, Docs

#16 회원가입 기능 구현 중 라우트 생성
  .prettierrc
  src/App.tsx
  src/components/Auth/ProfileSetup.tsx
  src/components/Auth/SetupEmail.tsx
  src/components/Auth/SetupKoreanIDInput.tsx
  src/components/Auth/SetupName.tsx
  src/components/Auth/SetupPassword.tsx
  src/components/Button.tsx
  src/components/ForSignUp/ProfileSetup.tsx
  src/components/ForSignUp/SetupName.tsx
  src/components/GenericForm.tsx
  src/components/layout/Layout.tsx
  src/hooks/useFunnel.tsx
  src/main.tsx
  src/pages/Home/Home.tsx
  src/pages/User/login/LoginPage.tsx
  src/pages/User/signup/SignUpPage.tsx
  src/router/route.tsx
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: Feat, Chore

#18 GPT4-mini 연동 및 테스트
  .gitignore
  src/hooks/useGPT.tsx
  src/pages/counseling/Counseling.tsx
Labels: Feat, Prompt

#20 기본 CSS 세팅
  src/App.tsx
  src/components/layout/Layout.tsx
  src/styles/GlobalStyles.tsx
  src/styles/Variables.tsx
  src/styles/theme.js
Labels: UI

#21 Feat : 회원가입 로직 최적화를 진행
  src/assets/Images/invalid.svg
  src/assets/Images/valid.svg
  src/assets/fonts/PretendardVariable.woff2
  src/components/Auth/AuthError.tsx
  src/components/Auth/CheckAgreement.tsx
  src/components/Auth/PageTitleHeader.tsx
  src/components/Auth/ProfileSetup.tsx
  src/components/Auth/SetupEmail.tsx
  src/components/Auth/SetupKoreanIDInput.tsx
  src/components/Auth/SetupName.tsx
  src/components/Auth/SetupPassword.tsx
  src/components/Auth/SignupProgressBar.tsx
  src/components/common/Button.tsx
  src/components/common/GenericForm.tsx
  src/components/common/Input.tsx
  src/components/common/ToolTip.tsx
  src/components/layout/Layout.tsx
  src/pages/User/signup/SignUpPage.tsx
  src/router/route.tsx
  src/styles/GlobalStyles.tsx
  src/utils/validation/handleValidation.ts
  vite.config.ts
Labels: Feat, Chore

#28 회원가입 플로우 완성 컴포넌트, 라우트 변경
  src/assets/Images/checkArrow.svg
  src/assets/Images/checkedArrow.svg
  src/assets/Images/welcome.svg
  src/components/Auth/AuthError.tsx
  src/components/Auth/CheckAgreement.tsx
  src/components/Auth/PageTitleHeader.tsx
  src/components/Auth/SetupEmail.tsx
  src/components/Auth/SetupKoreanIDInput.tsx
  src/components/Auth/SetupName.tsx
  src/components/Auth/SetupPassword.tsx
  src/components/common/Button.tsx
  src/components/common/GenericProgressBar.tsx
  src/components/common/Input.tsx
  src/components/common/ToolTip.tsx
  src/components/layout/Layout.tsx
  src/pages/User/signup/SignUpPage.tsx
  src/pages/User/welcome/WelcomePage.tsx
  src/router/route.tsx
Labels: Feat, Chore

#30 pwa 세팅작업 진행
  index.html
  public/icons/favicon.ico
  public/icons/logo-512x512.png
  public/manifest.json
  public/vite.svg
  sw.js
Labels: deploy

#31 Chore: pwa 세팅 실패로 다른 방법 시도
  index.html
  package-lock.json
  package.json
  public/icons/apple-touch-icon-180x180.png
  public/icons/favicon.ico
  public/icons/logo.svg
  public/icons/maskable-icon-512x512.png
  public/icons/pwa-192x192.png
  public/icons/pwa-512x512.png
  public/icons/pwa-64x64.png
  public/manifest.json
  tsconfig.tsbuildinfo
  vite.config.ts
Labels: Chore, deploy

#32 뷰포트 오류해결
  index.html
  vite.config.ts
Labels: Chore, deploy

#34 Feat/#27
  src/assets/Images/icon-send.svg
  src/assets/Images/img-speech-bubble.svg
  src/assets/Images/img-wish-emotion.svg
  src/pages/Home/Home.tsx
  src/pages/emotion/Emotion.tsx
  src/pages/emotion/record/EmotionBad.tsx
  src/pages/emotion/record/EmotionEffort.tsx
  src/pages/emotion/record/EmotionGood.tsx
  src/pages/emotion/record/EmotionRecord.style.tsx
  src/pages/emotion/record/EmotionRecord.tsx
  src/pages/emotion/record/EmotionRecordPage.tsx
  src/router/route.tsx
  src/styles/GlobalStyles.tsx
  src/styles/Variables.tsx
Labels: Feat

#36 Feat : 로그인 기능구현
  index.html
  src/assets/Images/logo.svg
  src/assets/Images/subfertility.svg
  src/assets/logo.svg
  src/components/Auth/PageTitleHeader.tsx
  src/components/Auth/ProfileSetup.tsx
  src/components/Auth/SetupEmail.tsx
  src/components/Auth/SetupName.tsx
  src/components/Auth/SetupSubfertility.tsx
  src/components/common/Button.tsx
  src/pages/User/login/LoginPage.tsx
  src/pages/User/signup/SignUpPage.tsx
  src/utils/constants.js
  src/utils/validation/handleValidation.ts
Labels: Feat, UI

#41 Feat: 난임 스트레스 척도 기능 구현
  public/img/testing-01.svg
  public/img/testing-02.svg
  public/img/testing-03.svg
  public/img/testing-04.svg
  public/img/testing-05.svg
  src/pages/scale/Questions.tsx
  src/pages/scale/Testing.tsx
  src/router/route.tsx
Labels: Feat, UI

#39 Feat: 심리 상담 가이드 기능 구현
  src/assets/Images/guideArrow.svg
  src/assets/Images/pageBack.svg
  src/assets/Images/sendIcon.svg
  src/assets/Images/wishProfile.svg
  src/pages/counseling/Counseling.tsx
Labels: Feat, UI

#43 Edit: counseling 아이콘 이름 파스칼케이스에서 => - 로 변경
  public/img/icon-guide-arrow.svg
  public/img/icon-page-prev.svg
  public/img/icon-send.svg
  public/img/icon-wish-profile.svg
  src/pages/counseling/Counseling.tsx
Labels: Chore

#38 메인페이지 ui 구현 1/5
  src/assets/Images/mainFemaleProfile.svg
  src/assets/Images/mainlock.svg
  src/components/common/Footer.tsx
  src/components/home/CoupleInfomation.tsx
  src/components/home/HomePageTitle.tsx
  src/pages/Home/Home.tsx
Labels: UI

#44 Style: 공통 스타일(레이아웃, 스크롤바, 인풋, 버튼) 추가 설정
  public/img/icon-check.svg
  src/components/common/Button.tsx
  src/components/layout/Layout.tsx
  src/styles/GlobalStyles.tsx
Labels: UI

#46 감정기록 플로우 작업 중
  index.html
  src/assets/Images/img-wish-husband.svg
  src/assets/Images/img-wish-wife.svg
  src/components/common/Toast.tsx
  src/pages/emotion/message/EmotionMessage.tsx
  src/pages/emotion/record/EmotionBad.tsx
  src/pages/emotion/record/EmotionEffort.tsx
  src/pages/emotion/record/EmotionGood.tsx
  src/pages/emotion/record/EmotionRecord.style.tsx
  src/pages/emotion/record/EmotionRecord.tsx
  src/pages/emotion/record/EmotionRecordPage.tsx
  src/store/useEmotionStore.ts
  src/styles/Variables.tsx
  vite.config.ts
Labels: Feat

#47 난임 스트레스 척도 : 버튼 고정, 공통 프로그레스바 이름 변경 반영
  src/pages/scale/Questions.tsx
  src/pages/scale/Testing.tsx
Labels: Bug, UI

#51 감정기록 이미지 폴더 이동 및 파일 경로 수정
  public/img/img-speech-bubble.svg
  public/img/img-wish-emotion.svg
  public/img/img-wish-husband.svg
  public/img/img-wish-wife.svg
  src/assets/Images/icon-send.svg
  src/pages/emotion/message/EmotionMessage.tsx
  src/pages/emotion/record/EmotionBad.tsx
  src/pages/emotion/record/EmotionEffort.tsx
  src/pages/emotion/record/EmotionGood.tsx
  src/pages/emotion/record/EmotionRecord.style.tsx
  src/pages/emotion/record/EmotionRecordPage.tsx
Labels: Chore, UI

#55 배포과정 타입 오류 제거
  src/components/Auth/SetupEmail.tsx
  src/components/Auth/SetupKoreanIDInput.tsx
  src/components/Auth/SetupName.tsx
  src/components/Auth/SetupPassword.tsx
  src/components/Auth/SetupSubfertility.tsx
  src/components/common/ToolTip.tsx
Labels: Hotfix, deploy

#56 Feat/#40
  public/img-wish-mission.svg
  src/assets/Images/invaildGray.svg
  src/pages/emotion/mission/EmotionMission.style.tsx
  src/pages/emotion/mission/EmotionMission.tsx
  src/router/route.tsx
Labels: Feat, UI

#57 Feat: 심리 상담 목록 UI 구현
  public/img/icon-counsling-record-delete.svg
  public/img/icon-search.svg
  public/img/icon-sort-arrow.svg
  public/img/no-counseling-record.svg
  src/pages/counseling/CounselingList.tsx
  src/pages/counseling/CounselingListItem.tsx
  src/router/route.tsx
  tsconfig.tsbuildinfo
Labels: UI

#60 Chore: ECharts 패키지 설치
  package-lock.json
  package.json
Labels: Chore

#61 감정분석 구현 완료
  src/hooks/useGPT.tsx
  src/pages/emotion/message/EmotionMessage.tsx
  src/store/useAnalysisStore.ts
  src/store/useEmotionStore.ts
Labels: Prompt

#63 감정분석 전역상태 전달 테스트 완료
  src/pages/emotion/message/EmotionMessage.tsx
  src/store/useAnalysisStore.ts
  src/store/useEmotionStore.ts
Labels: Feat

#64 AI 미션 추천 페이지 UI 구현 완료
  src/pages/emotion/mission/EmotionMission.style.tsx
  src/pages/emotion/mission/EmotionMission.tsx
  src/pages/emotion/mission/EmotionResult.tsx
  src/router/route.tsx
Labels: UI

#66 감정 분석 결과 페이지 UI 구현 진행중
  src/assets/Images/emotionResultSad.svg
  src/pages/emotion/mission/EmotionMission.style.tsx
  src/pages/emotion/mission/EmotionMission.tsx
  src/pages/emotion/mission/EmotionResult.tsx
  src/pages/emotion/result/EmotionResult.tsx
  src/router/route.tsx
Labels: UI

#67 감정 분석 페이지 데이터 시각화 진행중
  package-lock.json
  package.json
  src/pages/emotion/mission/EmotionMission.tsx
  src/pages/emotion/result/EmotionGraph.tsx
  src/pages/emotion/result/EmotionResult.tsx
  src/pages/emotion/result/EmotionStress.tsx
Labels: Feat, UI

#69 감정분석 결과 로그 추가
  src/pages/emotion/message/EmotionMessage.tsx
Labels: Chore, Hotfix

#71 난임스트레스척도 예상점수 프롬프트 수정
  src/pages/emotion/message/EmotionMessage.tsx
Labels: Hotfix, Prompt

#73 푸터 컴포넌트 ui 작업
  .gitignore
  prompt/.env
  public/img/footer-01.svg
  public/img/footer-02.svg
  public/img/footer-03.svg
  public/img/footer-04.svg
  src/assets/Images/mainManProfile.svg
  src/components/Auth/CheckAgreement.tsx
  src/components/Auth/SetupSubfertility.tsx
  src/components/common/Footer.tsx
  src/pages/Home/Home.tsx
Labels: UI
