Repository KDT-hahahoho/kdt_frontend, pull requests merged in 2024-11, with the labels that each got.

#76 난임 스트레스 척도 구현 및 프롬프팅
  src/pages/scale/Questions.tsx
  src/pages/scale/ScaleList.tsx
  src/pages/scale/Testing.tsx
  src/router/route.tsx
Labels: Feat, Prompt

#77 Feat:스트레스 척도 검사 결과 UI 구현
  public/img/icon-next.svg
  src/pages/scale/ScaleResult.tsx
  src/pages/scale/ScaleTotalGraph.tsx
  src/pages/scale/ScaleTypeGraph.tsx
  src/router/route.tsx
Labels: Feat, UI

#79 심리상담 프롬프팅 고도화
  src/pages/counseling/Counseling.tsx
Labels: Feat, Prompt

#80 부부 스트레스 척도 그래프 구현
  package-lock.json
  package.json
  src/components/home/OurReport.tsx
  src/pages/Home/Home.tsx
  tsconfig.tsbuildinfo
Labels: Feat

#83 난임 스트레스 척도 목록 : 통계 차트, 모달 노출
  src/components/common/Button.tsx
  src/pages/scale/ListGraph.tsx
  src/pages/scale/ScaleList.tsx
Labels: Feat, UI

#88 배포 시 감정기록 페이지 깨짐 현상 해결
  src/pages/emotion/message/EmotionMessage.style.tsx
  src/pages/emotion/record/EmotionRecord.style.tsx
Labels: Bug, UI

#82 메인 페이지 그래프 구현
  package-lock.json
  package.json
  src/components/common/Toogle.tsx
  src/components/home/CoupleInformation.tsx
  src/components/home/CoupleReport.tsx
  src/components/home/OurKeyword.tsx
  src/components/home/OurReport.tsx
  src/pages/Home/Home.tsx
Labels: Feat

#89 난임 스트레스 척도 목록 최적화
  src/pages/scale/ScaleList.tsx
  src/styles/GlobalStyles.tsx
Labels: Refactor, UI

#84 감정분석 결과 페이지 기능 구현
  src/pages/emotion/result/EmotionGraph.tsx
  src/pages/emotion/result/EmotionResult.tsx
  src/pages/emotion/result/EmotionStress.tsx
Labels: UI

#92 Feat : footer layout 수정
  src/components/common/Footer.tsx
Labels: Feat, UI

#93 Cont: 심리 상담 가이드 컴포넌트 분리
  src/pages/counseling/Counseling.tsx
  src/pages/counseling/CounslingGuide.tsx
Labels: UI

#96 전일 난임스트레스 예상점수 프롬프트에 반영
  src/pages/emotion/message/EmotionMessage.tsx
Labels: Hotfix, Prompt

#100 로그인 회원가입 기능 구현 & 푸터 수정
  src/components/Auth/ProfileSetup.tsx
  src/components/common/Footer.tsx
  src/pages/Home/Home.tsx
  src/pages/User/login/LoginPage.tsx
  src/pages/User/signup/SignUpPage.tsx
  src/router/ProtectedRoute.tsx
  src/store/useAuthStore.ts
  src/store/userStore.ts
  src/utils/validation/handleValidation.ts
  vite.config.ts
Labels: Feat

#102 부부연동 기능 개발 중
  public/img/img-wish-follow.svg
  src/pages/User/follow/FollowPage.tsx
  src/router/route.tsx
Labels: Feat

#99 감정분석 페이지 시각화 구체화
  src/pages/emotion/result/EmotionGraph.tsx
  src/pages/emotion/result/EmotionResult.tsx
  src/pages/emotion/result/EmotionStress.tsx
Labels: UI

#103 Feat : local 정보 수정 / 경로 수정
  src/components/home/HomePageTitle.tsx
  src/hooks/useAuthRedirect.tsx
  src/pages/Home/Home.tsx
  src/pages/User/welcome/WelcomePage.tsx
Labels: Feat

#106 부부연동 기능 구현 완료
  src/pages/User/follow/FollowPage.tsx
Labels: Feat, UI

#104 Cont: 심리 삼담 가이드 조건 추가
  src/pages/counseling/Counseling.tsx
Labels: Feat

#109 부부등록 기능을 구현한다.
  src/components/common/Toogle.tsx
  src/components/home/CoupleInformation.tsx
  src/components/home/CoupleReport.tsx
  src/components/home/HomePageTitle.tsx
  src/hooks/useCoupleInfo.tsx
  src/pages/User/follow/FollowPage.tsx
  src/pages/User/login/LoginPage.tsx
  src/pages/User/signup/SignUpPage.tsx
  src/store/useAuthStore.ts
Labels: Feat

#111 미션 UI , 관심사 그래프 구현
  package-lock.json
  package.json
  src/components/home/CoupleInformation.tsx
  src/components/home/CoupleMissonWeekly.tsx
  src/components/home/CoupleReport.tsx
  src/components/home/OurKeyword.tsx
  src/components/home/OurReport.tsx
Labels: Feat, UI

#112 관심사 등록 개발 완료
  public/img/img-wish-interest.svg
  src/pages/User/interests/InterestItem.tsx
  src/pages/User/interests/InterestPage.tsx
  src/pages/emotion/message/EmotionMessage.tsx
  src/router/route.tsx
  vite.config.ts
Labels: Feat, UI

#114 ✅ done: 감정 분석 키워드 불러오기 완료
  src/pages/emotion/message/EmotionMessage.tsx
Labels: Feat

#115 심리상담 AI 프롬프팅 고도화 진행중
  src/pages/counseling/Counseling.tsx
Labels: Prompt

#116 Feat/#24
  src/pages/scale/Questions.tsx
  src/pages/scale/Testing.tsx
  vite.config.ts
Labels: Feat

#117 척도 검사 버튼 활성화, 스크롤 조정
  src/pages/scale/Questions.tsx
  src/pages/scale/Testing.tsx
Labels: Feat

#118 척도 검사 리스트 데이터 GET
  src/pages/scale/ListGraph.tsx
  src/pages/scale/ScaleList.tsx
Labels: Feat

#119 척도 검사 리스트 데이터 정렬 순서 변경
  src/pages/scale/ListGraph.tsx
  src/pages/scale/ScaleList.tsx
Labels: Bug

#123 감정 분석 시 난임스트레스 척도 검사결과 반영
  src/pages/User/follow/FollowPage.tsx
  src/pages/User/interests/InterestPage.tsx
  src/pages/emotion/message/EmotionMessage.tsx
  src/types/types.ts
Labels: Feat, Hotfix

#124 ✅ done: 프롬프트 개선
  src/pages/emotion/message/EmotionMessage.tsx
Labels: Prompt

#125 Feat: 척도 검사 결과 GET 통신 및 결과 해석 모달 추가
  src/pages/scale/ScaleList.tsx
  src/pages/scale/ScaleResult.tsx
  src/pages/scale/ScaleTotalGraph.tsx
  src/pages/scale/ScaleTypeGraph.tsx
  src/router/route.tsx
  vite.config.ts
Labels: Feat

#126 Feat : 메인 데이터 패칭 구현
  src/assets/Images/notInftest.svg
  src/components/Auth/ProfileSetup.tsx
  src/components/Auth/SetupKoreanIDInput.tsx
  src/components/home/OurReport.tsx
  src/hooks/useGetCoupleData.tsx
  src/pages/Home/Home.tsx
  src/pages/User/login/LoginPage.tsx
  src/pages/User/signup/SignUpPage.tsx
  tsconfig.tsbuildinfo
Labels: Feat

#129 척도 검사 완료시 핵심신념 추출을 위한 데이터 변경
  src/pages/scale/Testing.tsx
Labels: Bug

#130 감정분석 결과 페이지 Fetch 기능을 구현한다
  public/img/img-wish-mission.svg
  src/pages/emotion/mission/EmotionMission.style.tsx
  src/pages/emotion/mission/EmotionMission.tsx
  src/pages/emotion/result/EmotionGraph.tsx
  src/pages/emotion/result/EmotionResult.tsx
  src/pages/emotion/result/EmotionStress.tsx
Labels: Feat, UI

#132 감정 기록 keyword 저장 형식 변경
  src/pages/emotion/message/EmotionMessage.tsx
  src/store/useAnalysisStore.ts
Labels: Hotfix

#133 emotions 프록시 설정
  vite.config.ts
Labels: Hotfix

#134 심리상담 프롬프팅 고도화 및 종료시 POST
  src/pages/counseling/Counseling.tsx
Labels: Feat, Prompt

#135 Member ID 반영
  src/pages/scale/ScaleList.tsx
  src/pages/scale/Testing.tsx
Labels: Bug

#138 AI 추천 미션 선택버튼 UI를 수정한다
  src/pages/emotion/mission/EmotionMission.style.tsx
Labels: UI

#140 난임 스트레스 척도 목록 데이터 없는 경우 예외 처리
  public/img/no-counseling-record.svg
  src/pages/scale/ListGraph.tsx
  src/pages/scale/ScaleList.tsx
Labels: Feat, UI

#142 푸터 redirect 수정, 모달 추가
  src/components/common/Footer.tsx
  src/pages/User/follow/FollowPage.tsx
  src/pages/User/interests/InterestPage.tsx
  src/pages/emotion/message/EmotionMessage.tsx
Labels: Hotfix

#149 Cont: 심리 상담 리스트 GET통신 및 목록 조건 처리
  src/pages/counseling/CounselingList.tsx
  src/pages/counseling/CounselingListItem.tsx
Labels: Feat

#151 심리상담 프롬프팅 고도화(최근 난임 점수 반영, 이전 상담 내역 전달)
  src/pages/counseling/Counseling.tsx
Labels: Feat, Prompt

#154 Cont: 심리 상담 가이드 width값 수정
  src/pages/counseling/CounslingGuide.tsx
Labels: Hotfix

#162 감정분석 결과 페이지 데이터 통신 기능을 수정한다
  src/pages/emotion/result/EmotionResult.tsx
Labels: Hotfix

#163 모바일 스크롤 오류 개선 테스트
  index.html
  src/pages/counseling/Counseling.tsx
Labels: Hotfix

#170 Hotfix: 심리 상담 리스트 오류 수정
  src/pages/counseling/CounselingList.tsx
  src/pages/counseling/CounselingListItem.tsx
Labels: Hotfix

#173 Feat: 타이틀 공통 컴포넌트 생성
  src/components/common/PageTitle.tsx
Labels: Feat

#174 모바일에서 인풋 활성화 시 발생하는 스크롤 오류 개선
  src/pages/counseling/Counseling.tsx
  src/pages/emotion/record/EmotionRecord.style.tsx
  src/styles/GlobalStyles.tsx
Labels: Hotfix

#175 배포
  index.html
  src/components/common/PageTitle.tsx
  src/components/home/CoupleInformation.tsx
  src/components/home/CoupleMissionWeekly.tsx
  src/components/home/CoupleReport.tsx
  src/components/home/OurKeyword.tsx
  src/components/home/OurReport.tsx
  src/hooks/useCoupleInfo.tsx
  src/hooks/useGetCoupleData.tsx
  src/pages/Home/Home.tsx
  src/pages/counseling/Counseling.tsx
  src/pages/counseling/CounselingList.tsx
  src/pages/counseling/CounselingListItem.tsx
  src/pages/emotion/message/EmotionMessage.tsx
  src/pages/emotion/record/EmotionRecord.style.tsx
  src/pages/emotion/result/EmotionResult.tsx
  src/store/usePrevRecordStore.ts
  src/styles/GlobalStyles.tsx
  src/types/types.ts
Labels: deploy

#177 Hotfix: 심리 상담 가이드 수정 및 상담 input 위치 수정
  src/pages/counseling/Counseling.tsx
  src/pages/counseling/CounslingGuide.tsx
Labels: Hotfix

#178 Style : 공통 타이틀 컴포넌트 bold 추가
  src/components/common/PageTitle.tsx
Labels: UI

#180 이어간 질문이 포함되도록 summary 프롬프팅 업데이트 및 채팅창 높이 변경
  src/pages/counseling/Counseling.tsx
Labels: Prompt, UI

#181 AI 심리상담 gpt 응답에 타이핑 효과 추가
  src/hooks/useTyping.tsx
  src/pages/counseling/Counseling.tsx
Labels: Feat

#186 EmotionStressBefore 공통 컴포넌트화
  src/components/home/CoupleReport.tsx
  src/pages/emotion/result/EmotionResult.tsx
  src/pages/emotion/result/EmotionStress.tsx
  src/pages/emotion/result/EmotionStressBefore.tsx
Labels: UI

#187 Feat:공통 타이틀 적용
  src/components/home/HomePageTitle.tsx
  src/pages/counseling/CounselingList.tsx
  src/pages/scale/ScaleList.tsx
  src/pages/scale/ScaleResult.tsx
  src/pages/scale/ScaleTotalGraph.tsx
  src/pages/scale/ScaleTypeGraph.tsx
Labels: Feat

#188 Cont: 공통 타이틀 Props 추가
  src/components/common/PageTitle.tsx
Labels: Feat

#191 배포
  src/components/common/PageTitle.tsx
  src/components/home/HomePageTitle.tsx
Labels: deploy

#197 심리상담 타이핑 효과 오류 개선, 감정분석 UI 개선
  src/hooks/useTyping.tsx
  src/pages/emotion/result/EmotionGraph.tsx
  src/pages/emotion/result/EmotionResult.tsx
  src/pages/emotion/result/EmotionStress.tsx
  src/pages/emotion/result/EmotionStressBefore.tsx
Labels: Bug, UI
